### ISSUE TITLE
gen/build.sh throws exception

### ISSUE THREAD

**Issue by ErikGrimes** [polymer-dart/polymerize_elements#2]
I realize this is all very early stage, but I wanted to try out a few elements not already generated.  So, I figured I'd add them and see what happens.  I ran build.sh and threw the exception below.

sdk: 1.22.0
os: osx 10.11.16

```
Analyzed app-toolbar
Start writing results: 

Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Wrote out/lib
Unhandled exception:
FileSystemException: Creation failed, path = 'out/lib' (OS Error: Not a directory, errno = 20)
#0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:90)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by dam0vm3nt** [comment]
Can you post the yaml descriptor too?

**Comment by dam0vm3nt** [comment]
It could just be that the `out` dir doesn't exist? Can you try creating it with `mkdir out`? I'll add it in any case in the code.

**Comment by ErikGrimes** [comment]
The process is actually creating a file ```out/lib``` where the text of the element is getting written.  Creating the directory causes the writer to fail because it expects to be able to write to that location.  I'm not sure why, but sometime it writes PaperInput and sometimes it writes PaperButton to ```out/lib```.

The pubspec:
```
name: polymer_elements
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://github.com/dam0vm3nt
description: Polymer-2 support for Dart

version: 2.0.0-preview.1
dependencies:
  polymer_element: any
  js: any
  html5: ^0.0.4
dependency_overrides:
#  polymer_element:
#   path: ../polymer_element
```
I've tried it with polymer_element/master as well as the latest published version in pub.  I've also tried it with polymerize/master and polymerize/v0.4.5.
