### ISSUE TITLE
iron-meta throws exception when created

### ISSUE THREAD

**Issue by ErikGrimes** [polymer-dart/polymerize_elements#4]
The issue occurs when created declaratively 
```
      <iron-meta key="info" value="foo/bar"></iron-meta>
```
or programmatically

```
  connectedCallback() {
    (document.createElement('iron-meta') as IronMeta)..key=validatorName..type=validatorType..value=this;
  }

```

![iron_meta_exception](https://cloud.githubusercontent.com/assets/1533326/23862431/006d707e-07db-11e7-918e-b4ded1307e57.png)

pubspec.lock
```
polymer_element:
    description:
      name: polymer_element
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.0"
  polymer_elements:
    description:
      ref: "v0.2.1"
      resolved-ref: dac21c67470183f7f27831cff023de94b8ab8fe2
      url: "https://github.com/polymer-dart/polymerize_elements.git"
    source: git
    version: "2.0.0-preview.1"
```

polymerize: ``` 0.7.0+1```
